# RTF parsing: page splitting, headers, cells, merges, escapes (fixtures
# are generated by tests/make_test_rtfs.R)

test_that("simple fixture parses to the expected structure", {
  pages <- parse_rtf(test_path("fixtures", "01_simple.rtf"))
  expect_length(pages, 1L)

  page <- pages[[1]]
  expect_identical(page$parameter, "Cholesterol")
  expect_identical(block_nrow(page$header), 1L)
  expect_identical(block_nrow(page$data), 3L)

  expect_true(all(page$header$is_header))
  expect_identical(page$header$text[1L, ],
                   c("Treatment Group", "N", "Mean", "SD"))
  expect_identical(page$header$width[1L, ],
                   c(2160L, 1440L, 1440L, 1440L))
  expect_identical(page$data$text[1L, 1L], "Placebo")
})

test_that("multi-parameter fixture exposes one parameter per page", {
  pages <- parse_rtf(test_path("fixtures", "02_multi_param.rtf"))
  expect_length(pages, 3L)
  expect_identical(get_parameters(pages),
                   c("Cholesterol", "Triglycerides", "HDL"))
})

test_that("timeline labels are detected across pages", {
  pages <- parse_rtf(test_path("fixtures", "03_multi_timeline.rtf"))
  expect_identical(get_timelines(pages),
                   c("Week 1", "Week 4", "Week 8", "Week 12"))
})

test_that("merged header cells get colspans and copied text", {
  pages <- parse_rtf(test_path("fixtures", "05_merged_headers.rtf"))
  hdrs <- pages[[1]]$header
  expect_identical(block_nrow(hdrs), 2L)

  expect_identical(hdrs$colspan[1L, ], c(1L, 2L, 0L, 2L, 0L))
  # Continuation cells carry the merge-first text
  expect_identical(hdrs$text[1L, 3L], "Dose A")
  expect_identical(hdrs$text[1L, 5L], "Dose B")
})

test_that("escape fixture decodes CP1252 and unicode in cells", {
  pages <- parse_rtf(test_path("fixtures", "07_escapes.rtf"))
  hdr  <- pages[[1]]$header
  dat  <- pages[[1]]$data

  expect_identical(hdr$text[1L, 2L], "Mean ± SD")
  expect_identical(hdr$text[1L, 3L], "“Range”")
  expect_identical(dat$text[1L, 1L], "≤ 5 years")
  expect_identical(dat$text[1L, 3L], "120–190")
  # \uc0 consumes the delimiter space and skips no fallback
  expect_identical(dat$text[2L, 1L], "Δfrom baseline")
})

test_that("whole-file CP1252 bytes are converted on read", {
  raw_1252 <- c(
    charToRaw("{\\rtf1\\ansi\n\\sectd\n\\trowd\\trhdr\\cellx2000{\\b M"),
    as.raw(0x93), charToRaw("q"), as.raw(0x94),
    charToRaw("\\b0\\cell}\\row\\trowd\\cellx2000{5.2\\cell}\\row\\sect}")
  )
  path <- tempfile(fileext = ".rtf")
  on.exit(unlink(path), add = TRUE)
  writeBin(raw_1252, path)

  pages <- parse_rtf(path)
  expect_identical(pages[[1]]$header$text[1L, 1L], "M“q”")
})

test_that("parsed cells contain no RTF artifacts", {
  # All table fixtures (06 is the image fixture, so skip it)
  fixtures <- list.files(test_path("fixtures"), pattern = "\\.rtf$",
                         full.names = TRUE)
  fixtures <- fixtures[!grepl("06_image", fixtures)]
  for (f in fixtures) {
    pages <- parse_rtf(f)
    for (page in pages) {
      for (b in list(page$header, page$data)) {
        texts <- b$text[b$present]
        for (txt in texts) {
          expect_false(
            grepl("[�□]", txt, perl = TRUE) ||
              grepl("\\\\[a-zA-Z]{2,}", txt, perl = TRUE),
            label = sprintf("artifact-free cell in %s ('%s')",
                            basename(f), txt)
          )
        }
      }
    }
  }
})
