# RTF parsing: page splitting, headers, cells, merges, escapes (fixtures
# are generated by tests/make_test_rtfs.R)

test_that("simple fixture parses to the expected structure", {
  pages <- parse_rtf(test_path("fixtures", "01_simple.rtf"))
  expect_length(pages, 1L)

  page <- pages[[1]]
  expect_identical(page$parameter, "Cholesterol")
  expect_length(page$header_rows, 1L)
  expect_length(page$data_rows, 3L)

  hdr <- page$header_rows[[1]]
  expect_true(hdr$is_header)
  expect_identical(
    vapply(hdr$cells, `[[`, character(1), "text"),
    c("Treatment Group", "N", "Mean", "SD")
  )
  expect_identical(
    vapply(hdr$cells, `[[`, numeric(1), "width_twips"),
    c(2160, 1440, 1440, 1440)
  )
  expect_identical(page$data_rows[[1]]$cells[[1]]$text, "Placebo")
})

test_that("multi-parameter fixture exposes one parameter per page", {
  pages <- parse_rtf(test_path("fixtures", "02_multi_param.rtf"))
  expect_length(pages, 3L)
  expect_identical(get_parameters(pages),
                   c("Cholesterol", "Triglycerides", "HDL"))
})

test_that("timeline labels are detected across pages", {
  pages <- parse_rtf(test_path("fixtures", "03_multi_timeline.rtf"))
  expect_identical(get_timelines(pages),
                   c("Week 1", "Week 4", "Week 8", "Week 12"))
})

test_that("merged header cells get colspans and copied text", {
  pages <- parse_rtf(test_path("fixtures", "05_merged_headers.rtf"))
  hdrs <- pages[[1]]$header_rows
  expect_length(hdrs, 2L)

  top <- hdrs[[1]]$cells
  expect_identical(vapply(top, `[[`, integer(1), "colspan"),
                   c(1L, 2L, 0L, 2L, 0L))
  # Continuation cells carry the merge-first text
  expect_identical(top[[3]]$text, "Dose A")
  expect_identical(top[[5]]$text, "Dose B")
})

test_that("escape fixture decodes CP1252 and unicode in cells", {
  pages <- parse_rtf(test_path("fixtures", "07_escapes.rtf"))
  hdr  <- pages[[1]]$header_rows[[1]]$cells
  rows <- pages[[1]]$data_rows

  expect_identical(hdr[[2]]$text, "Mean ± SD")
  expect_identical(hdr[[3]]$text, "“Range”")
  expect_identical(rows[[1]]$cells[[1]]$text, "≤ 5 years")
  expect_identical(rows[[1]]$cells[[3]]$text, "120–190")
  # \uc0 consumes the delimiter space and skips no fallback
  expect_identical(rows[[2]]$cells[[1]]$text, "Δfrom baseline")
})

test_that("whole-file CP1252 bytes are converted on read", {
  raw_1252 <- c(
    charToRaw("{\\rtf1\\ansi\n\\sectd\n\\trowd\\trhdr\\cellx2000{\\b M"),
    as.raw(0x93), charToRaw("q"), as.raw(0x94),
    charToRaw("\\b0\\cell}\\row\\trowd\\cellx2000{5.2\\cell}\\row\\sect}")
  )
  path <- tempfile(fileext = ".rtf")
  on.exit(unlink(path), add = TRUE)
  writeBin(raw_1252, path)

  pages <- parse_rtf(path)
  expect_identical(pages[[1]]$header_rows[[1]]$cells[[1]]$text,
                   "M“q”")
})

test_that("parsed cells contain no RTF artifacts", {
  # All table fixtures (06 is the image fixture, so skip it)
  fixtures <- list.files(test_path("fixtures"), pattern = "\\.rtf$",
                         full.names = TRUE)
  fixtures <- fixtures[!grepl("06_image", fixtures)]
  for (f in fixtures) {
    pages <- parse_rtf(f)
    for (page in pages) {
      for (row in c(page$header_rows, page$data_rows)) {
        for (cell in row$cells) {
          expect_false(
            grepl("[�□]", cell$text, perl = TRUE) ||
              grepl("\\\\[a-zA-Z]{2,}", cell$text, perl = TRUE),
            label = sprintf("artifact-free cell in %s ('%s')",
                            basename(f), cell$text)
          )
        }
      }
    }
  }
})
